version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  test-release:  
    executor:
      name: win/default
    steps:
      - checkout
      - run: dotnet test -c Release

  test-release-no-progress:  
    executor:
      name: win/default
    steps:
      - checkout
      - run: dotnet test -c Release_NoProgress

  test-debug:  
    executor:
      name: win/default
    steps:
      - checkout
      - run: dotnet test -c Debug

  test-debug-no-progress:  
    executor:
      name: win/default
    steps:
      - checkout
      - run: dotnet test -c Debug_NoProgress
            

workflows:
  unit-tests: 
    jobs:
      - test-release
      - test-release-no-progress
      - test-debug
      - test-debug-no-progress