version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  run-tests:
    parameters:
      config:
        type: string
      runtime:
        type: string
    executor:
      name: win/default
    steps:
      - checkout
      #-nodereuse:false to try to fix hang (see https://github.com/dotnet/sdk/issues/9452)
      - run:
          command: dotnet test -c <<parameters.config>> --framework <<parameters.runtime>> -nodereuse:false
          no_output_timeout: 60m

workflows:
  net5-tests:
    jobs:
      - run-tests:
          name: Net5 Release
          config: Release
          runtime: net5.0
      - run-tests:
          name: Net5 Release Without Progress
          config: Release_NoProgress
          runtime: net5.0
      - run-tests:
          name: Net5 Debug
          config: Debug
          runtime: net5.0
      - run-tests:
          name: Net5 Debug Without Progress
          config: Debug_NoProgress
          runtime: net5.0
         
  netframework-tests:
    jobs: 
      - run-tests:
          name: NetFramework Release
          config: Release
          runtime: net472
      - run-tests:
          name: NetFramework Release Without Progress
          config: Release_NoProgress
          runtime: net472
      - run-tests:
          name: NetFramework Debug
          config: Debug
          runtime: net472
      - run-tests:
          name: NetFramework Debug Without Progress
          config: Debug_NoProgress
          runtime: net472
