version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.4.0

jobs:
  build: # name of your job
    executor:
      name: win/default # executor type

    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout
      - run: Write-Host 'Hello, Windows'