version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build-and-test:  
    executor:
      name: win/default
    steps:
      - checkout
      - run: dotnet test 
            

workflows:
  unit-tests: 
    jobs:
      - build-and-test