version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  run-tests:
    executor:
      name: win/default
      size: medium
    parameters:
      config:
        type: string
      runtime:
        type: string
      poolType:
        type: string
      allowStackToUnwind:
        type: boolean
    steps:
      - checkout
      - run:
          name: Run Tests
          #-nodereuse:false to try to fix hang (see https://github.com/dotnet/sdk/issues/9452)
          command: |
            $ResultsFile = "$pwd/dotnet-test-results-<<parameters.runtime>>-<<parameters.config>>.xml"
            dotnet test -c <<parameters.config>> -f <<parameters.runtime>> -nodereuse:false --logger:"junit;LogFilePath=$ResultsFile" -p:ExtraDefineConstants=PROTO_PROMISE_<<parameters.poolType>> -p:AllowStackToUnwind=<<parameters.allowStackToUnwind>>
          no_output_timeout: 5h

      - store_test_results:
          path: dotnet-test-results-<<parameters.runtime>>-<<parameters.config>>.xml

      - store_artifacts:
          path: dotnet-test-results-<<parameters.runtime>>-<<parameters.config>>.xml

workflows:
  dotnet-tests:
    jobs:
      - run-tests:
          name: <<matrix.runtime>> <<matrix.config>> <<matrix.poolType>>
          matrix:
            parameters:
              config: [Release, Debug, Release_NoProgress, Debug_NoProgress]
              runtime: [net5.0, net472]
              poolType: [POOL_ENABLE, POOL_DISABLE]
              allowStackToUnwind: [true]
      # Just run each configuration with stack unwinding disabled to make sure it works. We don't need to test all runtimes or pool types for this.
      - run-tests:
          name: No-Stack-Unwind <<matrix.config>>
          matrix:
            parameters:
              config: [Release, Debug, Release_NoProgress, Debug_NoProgress]
              runtime: [net5.0]
              poolType: [POOL_ENABLE]
              allowStackToUnwind: [false]
