version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  run-tests:
    parameters:
      config:
        type: string
      runtime:
        type: string
      poolType:
        type: string
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: Run Tests
          #-nodereuse:false to try to fix hang (see https://github.com/dotnet/sdk/issues/9452)
          command: |
            if (<<parameters.runtime>> -eq Pool_Enabled) {
              $ExtraDefine = PROTO_PROMISE_POOL_ENABLE
            } else {
              $ExtraDefine = PROTO_PROMISE_POOL_DISABLE
            }
            $ResultsFile = "$pwd/dotnet-test-results-<<parameters.runtime>>-<<parameters.config>>.xml"
            dotnet test -c <<parameters.config>> -f <<parameters.runtime>> -nodereuse:false --logger:"junit;LogFilePath=$ResultsFile" -p:ExtraDefineConstants=$ExtraDefine
          no_output_timeout: 60m

      - store_test_results:
          path: dotnet-test-results-<<parameters.runtime>>-<<parameters.config>>.xml

      - store_artifacts:
          path: dotnet-test-results-<<parameters.runtime>>-<<parameters.config>>.xml

workflows:
  dotnet-tests:
    jobs:
      - run-tests:
          name: <<matrix.runtime>> <<matrix.config>> <<matrix.poolType>>
          matrix:
            parameters:
              config: [Release, Debug, Release_NoProgress, Debug_NoProgress]
              runtime: [net5.0, net472]
              poolType: [Pool_Enabled, Pool_Disabled]
