# This builds in all configurations and runtimes so we will catch any compilation errors prior to releasing with the automatic publish-nuget action.

name: CsProj Builds

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  csproj-build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        config: [Release, Debug]
        developerMode: [true, false]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
          
      - name: Build
        run: |
          dotnet build -c ${{ matrix.config }} -p:DeveloperMode=${{ matrix.developerMode }}
        timeout-minutes: 10
