# This builds in all configurations and runtimes so we will catch any compilation errors prior to releasing with the automatic publish-nuget action.

name: CsProj Builds

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  csproj-build:
    name: ${{ matrix.config }}-${{ matrix.devMode.name }}
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        config: [Release, Debug]
        devMode:
          - {
              name: devMode,
              value: true
            }
          - {
              name: userMode,
              value: false
            }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.X
          
      - name: Build Core
        run: |
          dotnet build -c ${{ matrix.config }} /p:DeveloperMode=${{ matrix.devMode.value }} /p:IsNugetBuild=true
        timeout-minutes: 10

      - name: Build Analyzer
        run: dotnet build ./ProtoPromise.Analyzer/ProtoPromise.Analyzer -c ${{ matrix.config }}
        timeout-minutes: 10
