name: .Net Framework Tests

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  dotnet-framework-tests:
    runs-on: windows-latest
    
    strategy:
      fail-fast: false
      matrix:
        config: [Release, Release_NoProgress, Debug, Debug_NoProgress]
        pooling: [POOL_ENABLE, POOL_DISABLE]
        exclude:
            # DEBUG mode forces pooling disabled.
          - config: Debug
            pooling: POOL_ENABLE
          - config: Debug_NoProgress
            pooling: POOL_ENABLE

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          global-json-file: global.json
          
      - name: Run Tests
        timeout-minutes: 180
        run: dotnet test -c ${{ matrix.config }} -f net472 --logger "trx;logfilename=dotnet-test-results-net472-${{ matrix.config }}-${{ matrix.pooling }}.trx" -p:ExtraDefineConstants=PROTO_PROMISE_${{ matrix.pooling }} --results-directory "./TestResults"

      - uses: dorny/test-reporter@v1
        if: always()
        with:
          name: dotnet-test-results-net472-${{ matrix.config }}-${{ matrix.pooling }}-${{ matrix.devString }}
          path: TestResults/*.trx
          reporter: dotnet-trx

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: dotnet-test-results-net472-${{ matrix.config }}-${{ matrix.pooling }}-${{ matrix.devString }}
          path: TestResults
