name: .Net Core Tests

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  dotnet-core-tests:
    name: Test (${{ matrix.config }}, ${{ matrix.objectPooling.name }}, ${{ matrix.devMode.name }})
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        config: [Release, Release_NoProgress, Debug, Debug_NoProgress]
        objectPooling:
          - {
              name: Pool_Enabled,
              symbol: PROTO_PROMISE_POOL_ENABLE
            }
          - {
              name: Pool_Disabled,
              symbol: PROTO_PROMISE_POOL_DISABLE
            }
        devMode:
          - {
              name: devMode,
              value: true
            }
          - {
              name: userMode,
              value: false
            }

        exclude:
          # DEBUG mode forces pooling disabled.
          - {
              config: Debug,
              objectPooling: { name: Pool_Enabled }
            }
          - {
              config: Debug_NoProgress,
              objectPooling: { name: Pool_Enabled }
            }

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
          
      - name: Run Tests
        run: |
          dotnet test -c ${{ matrix.config }} -f net6.0 --logger "trx;logfilename=dotnet-test-results-net6.0-${{ matrix.config }}-${{ matrix.objectPooling.name }}-${{ matrix.devMode.name }}.trx" -p:ExtraDefineConstants=${{ matrix.objectPooling.symbol }} -p:DeveloperMode=${{ matrix.devMode.value }} --results-directory "./TestResults"
        timeout-minutes: 120

      - uses: dorny/test-reporter@v1
        if: always()
        with:
          name: dotnet-test-results-net6.0-${{ matrix.config }}-${{ matrix.objectPooling.name }}-${{ matrix.devMode.name }}
          path: TestResults/*.trx
          reporter: dotnet-trx

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: dotnet-test-results-net6.0-${{ matrix.config }}-${{ matrix.objectPooling.name }}-${{ matrix.devMode.name }}
          path: TestResults
