name: DotNet Tests

on: [pull_request]

jobs:
  unity-tests:
    runs-on: windows-latest
    
    strategy:
      matrix:
        runtime: [Net5, NetFramework]
        configuration: [Release, Debug, Release_NoProgress, Debug_NoProgress]
        include:
          - runtime: Net5
            framework: net5.0
          - runtime: NetFramework
            framework: net472

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Run Tests
        #-nodereuse:false to try to fix hang (see https://github.com/dotnet/sdk/issues/9452)
        shell: pwsh
        run: |
          $ResultsFile = "$pwd/artifacts/dotnet-test-results-${{ matrix.runtime }}-${{ matrix.configuration }}.trx"
          dotnet test -c ${{ matrix.configuration }} -f ${{ matrix.framework }} -nodereuse:false --logger "trx;LogFileName=$ResultsFile"

      - uses: dorny/test-reporter@v1
        if: always()
        with:
          name: "dotnet-test-results-${{ matrix.runtime }}-${{ matrix.configuration }}"
          path: "artifacts/*.trx"
          reporter: dotnet-trx

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts
